### ISSUE TITLE
Memery Leak 

### ISSUE THREAD

**Issue by heronghua** [yidun/captcha-android-demo#10]
static Captcha.a 
reference Captcha.b
reference CaptchaConfiguration.a 

leaks XXXActivity

singleton referenced an Activity context caused memery leak

**Comment by shuwenyouxi** [comment]
@HuTianQi 安卓v3.1.1有一样的问题吗?若有,怎么解决

**Comment by heronghua** [comment]
Have you fixed this?

**Comment by HuTianQi** [comment]
3.1.2版本已修复，可以参看[ChangeLog]( https://github.com/yidun/captcha-android-demo/blob/master/ChangeLog.md)， @heronghua
