### ISSUE TITLE
请删除AR, FR, RU values 文件中的app_name

### ISSUE THREAD

**Issue by MingyangYan** [yidun/captcha-android-demo#16]
如题，
<string name="app_name">Captcha</string> 和自己的app中的“app_name” 重了，导致再用那三种语言的时候整个app的名字变成了“Captcha”。

谢谢

**Comment by HuTianQi** [comment]
好的，建议收到，这个是创建语言资源文件时AS自动生成的，作为SDK确实没保留的必要，下个版本中我们去掉这些语言资源中app_name字段。
