### ISSUE TITLE
charles抓包的时候图片加载不出来

### ISSUE THREAD

**Issue by thiskiller** [yidun/captcha-android-demo#18]
charles抓包的时候图片加载不出来，请问是怎么回事？

**Comment by liulingfeng** [comment]
需要配置自定义证书信任

**Comment by thiskiller** [comment]
> 

请问如何配置，没有找到相应的方法

**Comment by liulingfeng** [comment]
https://blog.csdn.net/guolin_blog/article/details/117192301 android:networkSecurityConfig配置

**Comment by thiskiller** [comment]
抓包的时候只有验证校验弹窗加载不出来，其它的都是正常的，而且整个app仅仅只有易盾有问题
