### ISSUE TITLE
[已解决]大部分设备适配都有问题

### ISSUE THREAD

**Issue by hloong** [yidun/captcha-android-demo#6]
红米3s，vivo x20，三星s8，华为mate9，全部都有问题
默认布局有问题，自己改了setPosition里的参数也有问题，整个窗口跟里面的图片都没有适配
似乎没有提供方法设置里面的图片的布局和大小？
![_20181201151727](https://user-images.githubusercontent.com/3353954/49325374-3cd2d500-f57c-11e8-88ca-89f0e24aeec2.jpg)
![_20181201151649](https://user-images.githubusercontent.com/3353954/49325376-3fcdc580-f57c-11e8-82c2-5183621cf2d2.jpg)

**Comment by AinialJing** [comment]
怎么解决的啊？
