### ISSUE TITLE
Source code of demo should be updated

### ISSUE THREAD

**Issue by Map-Hacker** [yidun/captcha-android-demo#7]
Current code is not usable anymore.

**Comment by HuTianQi** [comment]
是这样的，因为在客户对接中我们发现很多用户在使用SDK时都不怎么看接入文档，而是习惯复制粘贴demo中的示例代码，而dmeo中的代码为了展示所有功能，使用了验证码的所有可选功能，对于绝大部分用户而言可选功能是不需要的，这会造成客户会反过来问我们的技术支持一些问题，给我们的技术支持增加不必要的对接成本，所以之前考虑是否不在提供完整的示例dmeo，这样鼓励接入者去看README.md上的接入说明示例。也正因为如此验证码3.0.0版本开始对SDK的整体框架和API接口进行了重新设计，使得接入更加简单，基本无需参考示例dmeo。

**Comment by HuTianQi** [comment]
demo示例已更新
